### ISSUE TITLE
Finish adding the default data

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#1]
## Todos
- [x] Implement the necessary room classes
- [x] Create a populated db with the default data that is loaded on the first load of the app
- [x] Test the room classes

**Comment by MichaelBuessemeyer** [comment]
closed with #21
