### ISSUE TITLE
Add the calendar detail view

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#11]
## TODO:
- [ ] Add the header including the date to the view
- [ ] Add the information about the training done on that day to the view
- [ ] Add the sore muscles input on that day to the view
- [ ] Add the progress picture to the view
- [ ] Add the list of exercises performed on that day
  - [ ] Suggestion: Maybe this should be done in its own view that is opened once the user clicks on the summary of the training the person did on that day.
- [ ] Add the comment on the bottom
