### ISSUE TITLE
Implement the training preview that uses the database data for the suggested workout

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#12]
Part of epic #9 

## TODO
- [ ] The view should look like it is on Figma
    - [ ] The workout should have a random subset of exercises from the database
    - [ ] The workout should be split into warm-up, routine and stretching.
    - [ ] The reps and sets should be editable
    - [ ] There should be a button that opens a view with an explanation video for each exercise
    - [ ] There should be a button in the bottom right corner that start the workout as it is currently configured.
