### ISSUE TITLE
Implement the break view displayed during a workout

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#13]
Part of #9 

## TODO
  - [ ] During a break there should be a view 
    - [ ] counting down the break time, 
    - [ ] showing the process of the routine, 
    - [ ] previewing the next exercise 
    - [ ] and a button at the bottom right corner to skip the break.
