### ISSUE TITLE
Implement the finish view after a workout

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#15]
Part fo #9

## TODO:
- [ ] Add a workout-finished screen
  - [ ] Add the header and the congrats
  - [ ] Add the card with the summary of the workout
  - [ ] Add the confetti smilies
  - [ ] Add a button to take and save a progress picture
  - [ ] Show all exercises of the performed exercises. 
    - [ ] Each entry should have a small edit icon at the bottom right, that makes them editable 
  - [ ] Add a comment text field that will be saved with the performed workout
  - [ ] Add a confirm button at the bottom right border that takes the user to the home.
