### ISSUE TITLE
Create first proper version of the home screen

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#4]
## TODOs
- [ ] Add the profile picture to the top
- [ ] Add the current entered sore muscles preview
- [ ] Show info about the last training based on the data using the room classes
- [ ] Show sum-up info about the whole past training sessions using access to the room classes

**Comment by MichaelBuessemeyer** [comment]
depends on #6
