### ISSUE TITLE
Add the prompt to enter sore muscles to the home screen

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#5]
## TODOs
- [ ] Currently, there is no functionality that asks the user to enter their sore muscles if they haven't already today
- [ ] A pop-up card above the sore muscle preview. For the design look at the figma
- [ ] Once the user clicks on this card, the user should be redirected to the sore muscle edit view
