### ISSUE TITLE
Add content to the settings view

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#6]
## TODOs
- [ ] Add the top bar with the title "Settings"
- [ ] Add the profile picture with a small edit button
- [ ] Make the profile picture editable
- [ ] Add a field for the name and save it in the app's preferences
- [ ] Do the same for the settings:
  - [ ] age
  - [ ] Notification days & time
  - [ ] default break time
- [ ] Add a save button at the bottom right corner to save the changes
- [ ] Add a delete all data button at the bottom.
- [ ] The delete all data button should prompt the user whether really to delete all data or not. If the user confirms this, all data should be reset to the beginning.
