### ISSUE TITLE
Add functionality to the muscle pain view

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#8]
## TODO:
- [x] Add the title "Muscle Pain" to the view
- [x] Add the header to the muscle pain preview
- [x] Up to the person developing this feature:
  - [x] make the muscles clickable on the main view or create a subview for each body region and make them editable there.
  - [x] Add a turn button that switches between a front and a back view of the human muscle model.
- [x] Add the color legend explaining the color coding in the view
- [x] Add a save button at the bottom right corner
- ~[] If the user leaves the view without saving changes, the user should be prompted to save the changes or not.~   -> #33
