### ISSUE TITLE
Create the first version of the workout views

### ISSUE THREAD

**Issue by MichaelBuessemeyer** [MichaelBuessemeyer/MyTrainingsPal#9]
## TODOs
- [ ] Add the header to the view
- [ ] After confirming the time entered the user should be redirected to the next view that presents the suggested workout routine.
- [ ] Save the entered time in the app's preferences so this time will be suggested the next time the user opens up this view. 
- [ ] The view should look like it is on Figma
    - [ ] The workout should have a random subset of exercises from the database
    - [ ] The workout should be split into warm-up, routine and stretching.
    - [ ] The reps and sets should be editable
    - [ ] There should be a button that opens a view with an explanation video for each exercise
    - [ ] There should be a button in the bottom right corner that start the workout as it is currently configured.
- [ ] The "during-training" views should be implemented:
  - [ ] During a break there should be a view 
    - [ ] counting down the break time, 
    - [ ] showing the process of the routine, 
    - [ ] previewing the next exercise 
    - [ ] and a button at the bottom right corner to skip the break.
  - [ ] During an exercise there should be a view displaying 
    - [ ] the name of the exercise, 
    - [ ] a gif of the exercise, 
    - [ ] a link to the explanation video, 
    - [ ] an editable input to input the done reps
    - [ ] a button at the bottom right corner to confirm the input and move on to the next break
    - [ ] a preview of the next upcoming exercise
